// SPDX-FileCopyrightText: 2023 Dirk van der Walt <dirkvanderwalt@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later

Ext.define('RdMobile.view.vouchers.pnlVoucherDetail', {
    extend  	: 'Ext.Panel',
    xtype   	: 'pnlVoucherDetail',
    floated		: true,
    modal		: true,
    centered	: true,
    closable	: true,
    fullscreen 	: true,
    padding		: 6,
    iconCls 	: 'x-fa fa-info-circle',
    tpl		: new Ext.XTemplate(
		'<div class="detail-section">',
		'Personal Info',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Name :</div>',
			'<div class="item-value">{name}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Surname :</div>',
			'<div class="item-value">{surname}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Phone :</div>',
			'<div class="item-value">{phone}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Email :</div>',
			'<div class="item-value">{email}</div>',
		'</div>',
		'<div class="detail-section">',
		'RADIUS Related',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Realm :</div>',
			'<div class="item-value">{realm}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Profile :</div>',
			'<div class="item-value">{profile}</div>',
		'</div>',
		'<div class="detail-section">',
		'RADIUS Activity',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Accept :</div>',
			"<tpl if='last_accept_time_in_words==\"Never\"'>",
				'<div class="item-value clr-grey-dark">(Never)</div>',
			'<tpl else>',
				'<div class="item-value">{last_accept_time_in_words}</div>',
			'</tpl>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Accept NAS :</div>',
			'<div class="item-value">{last_accept_nas}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Reject :</div>',
			"<tpl if='last_reject_time_in_words==\"Never\"'>",
				'<div class="item-value clr-grey-dark">(Never)</div>',
			'<tpl else>',
				'<div class="item-value">{last_reject_time_in_words}</div>',
			'</tpl>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Reject NAS :</div>',
			'<div class="item-value">{last_reject_nas}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Reject Message :</div>',
			'<div class="item-value">{last_reject_message}</div>',
		'</div>',
		'<div class="detail-section">',
		'Other Info',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Static IP :</div>',
			'<div class="item-value">{static_ip}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Extra Name :</div>',
			'<div class="item-value">{extra_name}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Extra Value :</div>',
			'<div class="item-value">{extra_value}</div>',
		'</div>',
		'<div class="detail-section">',
		'History',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Created :</div>',
			'<div class="item-value">{created_in_words}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Modified :</div>',
			'<div class="item-value">{modified_in_words}</div>',
		'</div>',
    ),
    initialize: function (){
        const me = this;
        me.setTitle(me.user_name);
     	var d = me.r.getData();
     	me.setData(d) 
  	}
  	/*
  	
  	
  	*/
});
