Ext.define('RdMobile.view.permanentUsers.pnlPermanentUserDetail', {
    extend  	: 'Ext.Panel',
    xtype   	: 'pnlPermanentUserDetail',
    floated		: true,
    modal		: true,
    centered	: true,
    closable	: true,
    fullscreen 	: true,
    padding		: 6,
    iconCls : 'x-fa fa-info-circle',
    tpl		: new Ext.XTemplate(
        //'<div class="item-main">',
       // 	'{username}',
       // '</div>',
		'<div class="detail-section">',
		'Personal Info',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Name :</div>',
			'<div class="item-value">{name}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Surname :</div>',
			'<div class="item-value">{surname}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Phone :</div>',
			'<div class="item-value">{phone}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Email :</div>',
			'<div class="item-value">{email}</div>',
		'</div>',
		'<div class="detail-section">',
		'RADIUS Related',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Realm :</div>',
			'<div class="item-value">{realm}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Profile :</div>',
			'<div class="item-value">{profile}</div>',
		'</div>',
		'<div class="detail-section">',
		'RADIUS Activity',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Accept :</div>',
			"<tpl if='last_accept_time_in_words==\"Never\"'>",
				'<div class="item-value clr-grey-dark">(Never)</div>',
			'<tpl else>',
				'<div class="item-value">{last_accept_time_in_words}</div>',
			'</tpl>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Accept NAS :</div>',
			'<div class="item-value">{last_accept_nas}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Reject :</div>',
			"<tpl if='last_reject_time_in_words==\"Never\"'>",
				'<div class="item-value clr-grey-dark">(Never)</div>',
			'<tpl else>',
				'<div class="item-value">{last_reject_time_in_words}</div>',
			'</tpl>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Reject NAS :</div>',
			'<div class="item-value">{last_reject_nas}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Last Reject Message :</div>',
			'<div class="item-value">{last_reject_message}</div>',
		'</div>',
		'<div class="detail-section">',
		'Other Info',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Static IP :</div>',
			'<div class="item-value">{static_ip}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Extra Name :</div>',
			'<div class="item-value">{extra_name}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Extra Value :</div>',
			'<div class="item-value">{extra_value}</div>',
		'</div>',
		'<div class="detail-section">',
		'History',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Created :</div>',
			'<div class="item-value">{created_in_words}</div>',
		'</div>',
		'<div class="two-columns-grid">',
			'<div class="item-lbl">Modified :</div>',
			'<div class="item-value">{modified_in_words}</div>',
		'</div>',
    ),
    initialize: function (){
        const me = this;
        me.setTitle(me.user_name);
     	var d = me.r.getData();
     	me.setData(d) 
  	}
  	
  	/*
  	"username": "dirkvanderwalt@gmail.com@airport",
            "name": "",
            "surname": "",
            "address": "",
            "phone": "",
            "email": "dirkvanderwalt@gmail.com",
            "auth_type": "sql",
            "active": true,
            "last_accept_time": "2023-07-17T07:17:16+00:00",
            "last_accept_time_in_words": "9 hours ago",
            "last_reject_time": null,
            "last_reject_time_in_words": "Never",
            "last_accept_nas": "mcp_26",
            "last_reject_nas": null,
            "last_reject_message": null,
            "perc_time_used": null,
            "perc_data_used": 3,
            "data_used": 4136594,
            "data_cap": 104857600,
            "time_used": null,
            "time_cap": null,
            "time_cap_type": "soft",
            "data_cap_type": "hard",
            "realm": "Dev",
            "realm_id": 19,
            "profile": "Dev_User-Registration",
            "profile_id": 48,
            "from_date": null,
            "to_date": null,
            "track_auth": false,
            "track_acct": true,
            "static_ip": "",
            "extra_name": "mac",
            "extra_value": "68-17-29-D2-AC-63",
            "country_id": 4,
            "language_id": 4,
            "cloud_id": 23,
            "created": "2023-07-07T15:27:22+00:00",
            "created_in_words": "1 week ago",
            "modified": "2023-07-16T05:26:40+00:00",
            "modified_in_words": "1 day ago",
   	*/
});
